# Generated by Django 6.0.4 on 2026-05-05 10:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(help_text='Day number (1-indexed)')),
                ('label', models.CharField(max_length=50)),
                ('total_off_duty', models.FloatField(default=0.0)),
                ('total_sleeper_berth', models.FloatField(default=0.0)),
                ('total_driving', models.FloatField(default=0.0)),
                ('total_on_duty_not_driving', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(max_length=300)),
                ('pickup_location', models.CharField(max_length=300)),
                ('dropoff_location', models.CharField(max_length=300)),
                ('current_cycle_used', models.FloatField(help_text='Hours used in current 70-hr/8-day cycle')),
                ('total_distance_miles', models.FloatField(blank=True, null=True)),
                ('total_duration_hours', models.FloatField(blank=True, null=True)),
                ('route_geometry', models.JSONField(blank=True, help_text='GeoJSON LineString for map display', null=True)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lon', models.FloatField(blank=True, null=True)),
                ('pickup_lat', models.FloatField(blank=True, null=True)),
                ('pickup_lon', models.FloatField(blank=True, null=True)),
                ('dropoff_lat', models.FloatField(blank=True, null=True)),
                ('dropoff_lon', models.FloatField(blank=True, null=True)),
                ('total_driving_hours', models.FloatField(blank=True, null=True)),
                ('trip_duration_hours', models.FloatField(blank=True, null=True)),
                ('total_days', models.IntegerField(blank=True, null=True)),
                ('cycle_hours_after', models.FloatField(blank=True, null=True)),
                ('num_rest_stops', models.IntegerField(default=0)),
                ('num_fuel_stops', models.IntegerField(default=0)),
                ('num_breaks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyLogSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('driving', 'Driving'), ('off_duty', 'Off Duty'), ('on_duty_not_driving', 'On Duty (Not Driving)'), ('sleeper_berth', 'Sleeper Berth')], max_length=30)),
                ('start_hour', models.FloatField(help_text='Hours since midnight of this day (0–24)')),
                ('end_hour', models.FloatField(help_text='Hours since midnight of this day (0–24)')),
                ('duration', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='trip.dailylog')),
            ],
            options={
                'ordering': ['start_hour'],
            },
        ),
        migrations.AddField(
            model_name='dailylog',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trip.trip'),
        ),
        migrations.CreateModel(
            name='TripSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('driving', 'Driving'), ('off_duty', 'Off Duty'), ('on_duty_not_driving', 'On Duty (Not Driving)'), ('sleeper_berth', 'Sleeper Berth')], max_length=30)),
                ('start', models.FloatField(help_text='Hours since trip Day 1 midnight')),
                ('end', models.FloatField(help_text='Hours since trip Day 1 midnight')),
                ('duration', models.FloatField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('miles', models.FloatField(default=0.0)),
                ('day', models.IntegerField(help_text='Which day of the trip (1-indexed)')),
                ('start_time', models.CharField(help_text='HH:MM within the day', max_length=10)),
                ('end_time', models.CharField(help_text='HH:MM within the day', max_length=10)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='trip.trip')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('start', 'Trip Start'), ('pickup', 'Pickup'), ('fuel', 'Fuel Stop'), ('rest', 'Rest Stop'), ('dropoff', 'Dropoff')], max_length=20)),
                ('location', models.CharField(max_length=300)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('hour_absolute', models.FloatField(help_text='Hours since trip Day 1 midnight')),
                ('time_label', models.CharField(max_length=50)),
                ('duration_hours', models.FloatField(default=0.0)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trip.trip')),
            ],
            options={
                'ordering': ['order', 'hour_absolute'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailylog',
            unique_together={('trip', 'day')},
        ),
    ]
