# Generated by Django 6.0.4 on 2026-05-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='cycle_hours_after',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='cycle_hours_remaining',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
