# Generated by Django 6.0.4 on 2026-05-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_dailylog_cycle_hours_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripstop',
            name='stop_type',
            field=models.CharField(choices=[('start', 'Trip Start'), ('pickup', 'Pickup'), ('fuel', 'Fuel Stop'), ('rest', 'Rest Stop'), ('break', '30-Min Break'), ('dropoff', 'Dropoff')], max_length=20),
        ),
    ]
