# Generated by Django 6.0.4 on 2026-05-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_alter_tripstop_stop_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylogsegment',
            name='miles',
            field=models.FloatField(default=0.0),
        ),
    ]
